import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { Product, QuoteItem, Quotation, RFQ, Sale, Delivery, Invoice, Notification } from '../types';

interface DemoState {
  // Data
  _seeded: boolean;
  products: Product[];
  quoteList: QuoteItem[];
  rfqs: RFQ[];
  quotations: Quotation[];
  sales: Sale[];
  deliveries: Delivery[];
  invoices: Invoice[];
  notifications: Notification[];
  
  // Actions
  setProducts: (products: Product[]) => void;
  updateProduct: (id: string, updates: Partial<Product>) => void;
  
  addToQuote: (productId: string, qty: number) => void;
  removeFromQuote: (productId: string) => void;
  updateQuoteQty: (productId: string, qty: number) => void;
  clearQuote: () => void;
  
  generateQuotation: (customerInfo: Quotation['customerInfo']) => Quotation | null;
  submitManualRFQ: (customerInfo: RFQ['customerInfo']) => RFQ | null;
  
  acceptQuotation: (quotationId: string) => void;
  
  addNotification: (notification: Omit<Notification, 'id' | 'date' | 'read'>) => void;
  markNotificationRead: (id: string) => void;
  
  resetDemo: () => void;
}

export const useDemoStore = create<DemoState>()(
  persist(
    (set, get) => ({
      _seeded: false,
      products: [],
      quoteList: [],
      rfqs: [],
      quotations: [],
      sales: [],
      deliveries: [],
      invoices: [],
      notifications: [],
      
      setProducts: (products) => set({ products }),
      
      updateProduct: (id, updates) => set((state) => ({
        products: state.products.map(p => p.id === id ? { ...p, ...updates } : p)
      })),
      
      addToQuote: (productId, qty) => set((state) => {
        const existing = state.quoteList.find(q => q.productId === productId);
        if (existing) {
          return {
            quoteList: state.quoteList.map(q => 
              q.productId === productId ? { ...q, qty: q.qty + qty } : q
            )
          };
        }
        const product = state.products.find(p => p.id === productId);
        if (!product) return state;
        return {
          quoteList: [...state.quoteList, { productId, qty, unit: product.unit }]
        };
      }),
      
      removeFromQuote: (productId) => set((state) => ({
        quoteList: state.quoteList.filter(q => q.productId !== productId)
      })),
      
      updateQuoteQty: (productId, qty) => set((state) => ({
        quoteList: state.quoteList.map(q => q.productId === productId ? { ...q, qty } : q)
      })),
      
      clearQuote: () => set({ quoteList: [] }),
      
      generateQuotation: (customerInfo) => {
        const state = get();
        if (state.quoteList.length === 0) return null;
        
        // Check if any product is MANUAL
        const hasManual = state.quoteList.some(q => {
          const p = state.products.find(prod => prod.id === q.productId);
          return p && p.quotationMode === "MANUAL";
        });
        
        if (hasManual) {
          // Should use submitManualRFQ instead, but safety check here
          return null;
        }
        
        const quotationNo = `QT-2026-${String(state.quotations.length + 100).padStart(4, '0')}`;
        const date = new Date().toISOString().split('T')[0];
        
        // valid until 7 days
        const validDate = new Date();
        validDate.setDate(validDate.getDate() + 7);
        const validUntil = validDate.toISOString().split('T')[0];
        
        let subtotal = 0;
        const lines = state.quoteList.map(q => {
          const product = state.products.find(p => p.id === q.productId)!;
          const quotedUnitPrice = product.internalPriceKwd;
          subtotal += quotedUnitPrice * q.qty;
          return {
            productId: q.productId,
            qty: q.qty,
            unit: q.unit,
            quotedUnitPrice
          };
        });
        
        const newQuotation: Quotation = {
          id: `q_${Date.now()}`,
          quotationNo,
          date,
          validUntil,
          source: "Website Auto",
          customerInfo,
          lines,
          subtotal,
          status: "DRAFT"
        };
        
        set((state) => ({
          quotations: [newQuotation, ...state.quotations],
          quoteList: []
        }));
        
        get().addNotification({
          title: "New Website Quotation",
          message: `${quotationNo} generated by ${customerInfo.company}.`
        });
        
        return newQuotation;
      },
      
      submitManualRFQ: (customerInfo) => {
        const state = get();
        if (state.quoteList.length === 0) return null;
        
        const rfqNo = `RFQ-2026-${String(state.rfqs.length + 100).padStart(4, '0')}`;
        const date = new Date().toISOString().split('T')[0];
        
        const newRFQ: RFQ = {
          id: `rfq_${Date.now()}`,
          rfqNo,
          date,
          source: "Website",
          customerInfo,
          lines: [...state.quoteList],
          status: "New"
        };
        
        set((state) => ({
          rfqs: [newRFQ, ...state.rfqs],
          quoteList: []
        }));
        
        get().addNotification({
          title: "New Website RFQ",
          message: `${rfqNo} received from ${customerInfo.company}.`
        });
        
        return newRFQ;
      },
      
      acceptQuotation: (quotationId) => {
        const state = get();
        const quotation = state.quotations.find(q => q.id === quotationId);
        if (!quotation || quotation.status === "ACCEPTED") return;
        
        const saleNo = `SO-2026-${String(state.sales.length + 100).padStart(4, '0')}`;
        const deliveryNo = `DO-2026-${String(state.deliveries.length + 100).padStart(4, '0')}`;
        const invoiceNo = `INV-2026-${String(state.invoices.length + 100).padStart(4, '0')}`;
        const date = new Date().toISOString().split('T')[0];
        
        const newSale: Sale = {
          id: `so_${Date.now()}`,
          saleNo,
          quotationId,
          date,
          customerName: quotation.customerInfo.company,
          amount: quotation.subtotal,
          status: "Confirmed"
        };
        
        const newDelivery: Delivery = {
          id: `do_${Date.now()}`,
          deliveryNo,
          saleId: newSale.id,
          date,
          customerName: quotation.customerInfo.company,
          area: quotation.customerInfo.area,
          status: "Preparing"
        };
        
        const newInvoice: Invoice = {
          id: `inv_${Date.now()}`,
          invoiceNo,
          saleId: newSale.id,
          date,
          customerName: quotation.customerInfo.company,
          amount: quotation.subtotal,
          balance: quotation.subtotal,
          status: "Draft"
        };
        
        set((state) => ({
          quotations: state.quotations.map(q => q.id === quotationId ? { ...q, status: "ACCEPTED" } : q),
          sales: [newSale, ...state.sales],
          deliveries: [newDelivery, ...state.deliveries],
          invoices: [newInvoice, ...state.invoices]
        }));
        
        get().addNotification({
          title: "Quotation Accepted",
          message: `${quotation.quotationNo} was accepted by ${quotation.customerInfo.company}.`
        });
      },
      
      addNotification: (notification) => set((state) => ({
        notifications: [
          {
            ...notification,
            id: `notif_${Date.now()}_${Math.random()}`,
            date: new Date().toISOString(),
            read: false
          },
          ...state.notifications
        ]
      })),
      
      markNotificationRead: (id) => set((state) => ({
        notifications: state.notifications.map(n => n.id === id ? { ...n, read: true } : n)
      })),
      
      resetDemo: () => {
        localStorage.removeItem('shieldmax-demo-storage-v3');
        window.location.reload();
      }
    }),
    {
      name: 'shieldmax-demo-storage-v3',
      onRehydrateStorage: () => {
        return (state) => {
          // After hydration completes, seed if needed
          if (state && !state._seeded) {
            // Dynamically import seed data to avoid circular deps
            import('../data/products').then(({ MOCK_PRODUCTS }) => {
              const currentState = useDemoStore.getState();
              if (currentState._seeded || currentState.products.length > 0) return;
              
              useDemoStore.setState({
                _seeded: true,
                products: MOCK_PRODUCTS,
                rfqs: [
                  {
                    id: "rfq_1",
                    rfqNo: "RFQ-2026-0098",
                    date: "2026-09-10",
                    source: "Website",
                    customerInfo: {
                      company: "Al Sabah Contracting W.L.L.",
                      contact: "Fahad Al Sabah",
                      phone: "+965 9900 1122",
                      email: "purchasing@alsabah.test",
                      area: "Shuwaikh",
                      project: "Warehouse Expansion",
                    },
                    lines: [
                      { productId: "p1", qty: 100, unit: "PAIR" },
                      { productId: "p4", qty: 20, unit: "PCS" }
                    ],
                    status: "New"
                  }
                ],
                quotations: [
                  {
                    id: "q_1",
                    quotationNo: "QT-2026-0082",
                    date: "2026-09-12",
                    validUntil: "2026-09-22",
                    source: "Manual",
                    customerInfo: {
                      company: "Gulf Industrial Services Co.",
                      contact: "Omar Tariq",
                      phone: "+965 6677 8899",
                      email: "omar@gulfindustrial.test",
                      area: "Mina Abdullah",
                      project: "Maintenance Shutdown",
                    },
                    lines: [
                      { productId: "p6", qty: 200, unit: "PCS", quotedUnitPrice: 1.500 },
                      { productId: "p3", qty: 50, unit: "PAIR", quotedUnitPrice: 4.850 }
                    ],
                    subtotal: 542.500,
                    status: "SENT"
                  }
                ],
                sales: [
                  {
                    id: "so_1",
                    saleNo: "SO-2026-0051",
                    quotationId: "q_0",
                    date: "2026-09-01",
                    customerName: "Kuwait Facility Solutions",
                    amount: 1540.750,
                    status: "Confirmed"
                  }
                ],
                deliveries: [
                  {
                    id: "do_1",
                    deliveryNo: "DO-2026-0046",
                    saleId: "so_1",
                    date: "2026-09-05",
                    customerName: "Kuwait Facility Solutions",
                    area: "Kuwait City",
                    status: "Preparing"
                  }
                ],
                invoices: [
                  {
                    id: "inv_1",
                    invoiceNo: "INV-2026-0060",
                    saleId: "so_1",
                    date: "2026-09-08",
                    customerName: "Kuwait Facility Solutions",
                    amount: 1540.750,
                    balance: 1540.750,
                    status: "Sent"
                  }
                ]
              });
            });
          }
        };
      }
    }
  )
);
